args <- commandArgs(trailingOnly=TRUE)
setwd(args[1]);source('report_helpers.R');b<-read_bundle('.')
stopifnot(length(group_topics(b))==11)
stopifnot(inherits(plot_groups(b),'ggplot'),inherits(plot_group_totals(b),'ggplot'),inherits(plot_changes(b),'ggplot'))
t<-friendly_table(b)
stopifnot(identical(names(t),c('Disease','Cases in 2019','Cases in 2025','Change')))
stopifnot(t[t$Disease=='Influenza','Change']=='+148.7%')
s<-summary_cards(b);stopifnot(grepl('+124%',s,fixed=TRUE),grepl('+21%',s,fixed=TRUE),grepl('-3%',s,fixed=TRUE))
cat('Dashboard data labels and ggplot2 checks passed\n')
